# -*- coding: utf-8 -*-
import json
from bs4 import BeautifulSoup

string = '''
<select>
<option value="4">Afghanistan</option>
<option value="247">Åland Islands</option>
<option value="7">Albania</option>
<option value="5">Algeria</option>
<option value="11">American Samoa</option>
<option value="9">Andorra</option>
<option value="10">Angola</option>
<option value="15">Anguilla</option>
<option value="16">Antarctica</option>
<option value="2">Antigua and Barbuda</option>
<option value="12">Argentina</option>
<option value="8">Armenia</option>
<option value="1">Aruba</option>
<option value="13">Australia</option>
<option value="14">Austria</option>
<option value="6">Azerbaijan</option>
<option value="22">Bahamas</option>
<option value="17">Bahrain</option>
<option value="23">Bangladesh</option>
<option value="18">Barbados</option>
<option value="28">Belarus</option>
<option value="21">Belgium</option>
<option value="24">Belize</option>
<option value="27">Benin</option>
<option value="20">Bermuda</option>
<option value="31">Bhutan</option>
<option value="26">Bolivia</option>
<option value="163">Bonaire, St Eustatius, Saba</option>
<option value="25">Bosnia &amp; Herzegovina</option>
<option value="19">Botswana</option>
<option value="33">Bouvet Island</option>
<option value="30">Brazil</option>
<option value="104">British Indian Ocean</option>
<option value="34">Brunei</option>
<option value="32">Bulgaria</option>
<option value="224">Burkina Faso</option>
<option value="35">Burundi</option>
<option value="37">Cambodia</option>
<option value="46">Cameroon</option>
<option value="36">Canada</option>
<option value="53">Cape Verde</option>
<option value="44">Cayman Islands</option>
<option value="51">Central African Rep.</option>
<option value="38">Chad</option>
<option value="43">Chile</option>
<option value="42">China</option>
<option value="119">Christmas Island</option>
<option value="45">Cocos (Keeling) Is.</option>
<option value="48">Colombia</option>
<option value="47">Comoros</option>
<option value="41">Congo, Dem. Rep</option>
<option value="40">Congo, Republic</option>
<option value="54">Cook Islands</option>
<option value="50">Costa Rica</option>
<option value="108">Cote d"'"Ivoire</option>
<option value="98">Croatia</option>
<option value="52">Cuba</option>
<option value="244">Curaçao</option>
<option value="55">Cyprus</option>
<option value="68">Czechia</option>
<option value="56">Denmark</option>
<option value="57">Djibouti</option>
<option value="58">Dominica</option>
<option value="59">Dominican Republic</option>
<option value="60">Ecuador</option>
<option value="61">Egypt</option>
<option value="66">El Salvador</option>
<option value="63">Equatorial Guinea</option>
<option value="65">Eritrea</option>
<option value="64">Estonia</option>
<option value="237">Eswatini</option>
<option value="67">Ethiopia</option>
<option value="72">Falkland Islands</option>
<option value="74">Faroe Islands</option>
<option value="71">Fiji</option>
<option value="70">Finland</option>
<option value="76">France</option>
<option value="77">French Antarctic</option>
<option value="69">French Guiana</option>
<option value="75">French Polynesia</option>
<option value="79">Gabon</option>
<option value="78">Gambia</option>
<option value="80">Georgia</option>
<option value="86">Germany</option>
<option value="81">Ghana</option>
<option value="82">Gibraltar</option>
<option value="89">Greece</option>
<option value="85">Greenland</option>
<option value="83">Grenada</option>
<option value="87">Guadeloupe</option>
<option value="88">Guam</option>
<option value="90">Guatemala</option>
<option value="84">Guernsey</option>
<option value="91">Guinea</option>
<option value="175">Guinea-Bissau</option>
<option value="92">Guyana</option>
<option value="94">Haiti</option>
<option value="96">Heard &amp; McDonald Is</option>
<option value="232">Holy See (Vatican City)</option>
<option value="97">Honduras</option>
<option value="95">Hong Kong (China)</option>
<option value="99">Hungary</option>
<option value="100">Iceland</option>
<option value="103">India</option>
<option value="101">Indonesia</option>
<option value="105">Iran</option>
<option value="109">Iraq</option>
<option value="62">Ireland</option>
<option value="102">Isle of Man</option>
<option value="106">Israel</option>
<option value="107">Italy</option>
<option value="112">Jamaica</option>
<option value="110">Japan</option>
<option value="111">Jersey</option>
<option value="113">Jordan</option>
<option value="121">Kazakhstan</option>
<option value="114">Kenya</option>
<option value="117">Kiribati</option>
<option value="118">Korea, South</option>
<option value="120">Kuwait</option>
<option value="115">Kyrgyzstan</option>
<option value="122">Laos</option>
<option value="124">Latvia</option>
<option value="123">Lebanon</option>
<option value="129">Lesotho</option>
<option value="126">Liberia</option>
<option value="131">Libya</option>
<option value="128">Liechtenstein</option>
<option value="125">Lithuania</option>
<option value="130">Luxembourg</option>
<option value="134">Macau (China)</option>
<option value="132">Madagascar</option>
<option value="139">Malawi</option>
<option value="150">Malaysia</option>
<option value="148">Maldives</option>
<option value="141">Mali</option>
<option value="146">Malta</option>
<option value="178">Marshall Islands</option>
<option value="133">Martinique</option>
<option value="145">Mauritania</option>
<option value="144">Mauritius</option>
<option value="136">Mayotte</option>
<option value="149">Mexico</option>
<option value="73">Micronesia</option>
<option value="135">Moldova</option>
<option value="142">Monaco</option>
<option value="137">Mongolia</option>
<option value="246">Montenegro</option>
<option value="138">Montserrat</option>
<option value="143">Morocco</option>
<option value="151">Mozambique</option>
<option value="242">Myanmar</option>
<option value="233">Namibia</option>
<option value="161">Nauru</option>
<option value="160">Nepal</option>
<option value="158">Netherlands</option>
<option value="152">New Caledonia</option>
<option value="165">New Zealand</option>
<option value="164">Nicaragua</option>
<option value="155">Niger</option>
<option value="157">Nigeria</option>
<option value="153">Niue</option>
<option value="154">Norfolk Island</option>
<option value="140">North Macedonia</option>
<option value="49">Northern Mariana Is.</option>
<option value="159">Norway</option>
<option value="147">Oman</option>
<option value="169">Pakistan</option>
<option value="174">Palau</option>
<option value="93">Palestine</option>
<option value="171">Panama</option>
<option value="173">Papua New Guinea</option>
<option value="166">Paraguay</option>
<option value="168">Peru</option>
<option value="180">Philippines</option>
<option value="167">Pitcairn Islands</option>
<option value="170">Poland</option>
<option value="172">Portugal</option>
<option value="181">Puerto Rico</option>
<option value="176">Qatar</option>
<option value="177">Reunion</option>
<option value="179">Romania</option>
<option value="182">Russia</option>
<option value="183">Rwanda</option>
<option value="248">Saint Barthélemy</option>
<option value="190">Saint Helena</option>
<option value="197">Saint Lucia</option>
<option value="249">Saint Martin</option>
<option value="236">Samoa</option>
<option value="193">San Marino</option>
<option value="211">Sao Tome &amp; Principe</option>
<option value="184">Saudi Arabia</option>
<option value="189">Senegal</option>
<option value="238">Serbia</option>
<option value="187">Seychelles</option>
<option value="192">Sierra Leone</option>
<option value="194">Singapore</option>
<option value="245">Sint Maarten</option>
<option value="127">Slovakia</option>
<option value="191">Slovenia</option>
<option value="29">Solomon Islands</option>
<option value="195">Somalia</option>
<option value="188">South Africa</option>
<option value="201">South Georgia Island</option>
<option value="243">South Sudan</option>
<option value="196">Spain</option>
<option value="39">Sri Lanka</option>
<option value="186">St Kitts &amp; Nevis</option>
<option value="185">St Pierre &amp;  Miquelon</option>
<option value="227">St Vincent Grenadines</option>
<option value="198">Sudan</option>
<option value="162">Suriname</option>
<option value="199">Svalbard &amp; Jan Mayen</option>
<option value="200">Sweden</option>
<option value="203">Switzerland</option>
<option value="202">Syria</option>
<option value="216">Taiwan (China)</option>
<option value="206">Tajikistan</option>
<option value="218">Tanzania</option>
<option value="205">Thailand</option>
<option value="213">Timor Leste</option>
<option value="210">Togo</option>
<option value="208">Tokelau</option>
<option value="209">Tonga</option>
<option value="204">Trinidad and Tobago</option>
<option value="212">Tunisia</option>
<option value="214">Turkey</option>
<option value="217">Turkmenistan</option>
<option value="207">Turks &amp; Caicos Is.</option>
<option value="215">Tuvalu</option>
<option value="219">Uganda</option>
<option value="222">Ukraine</option>
<option value="3">United Arab Emirates</option>
<option value="220">United Kingdom</option>
<option value="223">United States</option>
<option value="225">Uruguay</option>
<option value="221">US Minor Outlying Is</option>
<option value="226">Uzbekistan</option>
<option value="156">Vanuatu</option>
<option value="228">Venezuela</option>
<option value="230">Vietnam</option>
<option value="229">Virgin Islands (British)</option>
<option value="231">Virgin Islands (US)</option>
<option value="234">Wallis and Futuna</option>
<option value="235">Western Sahara</option>
<option value="239">Yemen</option>
<option value="240">Zambia</option>
<option value="241">Zimbabwe</option>
</select>
'''

jsonfile = []
# Initializing an HTML parser using BeautifulSoup
soup = BeautifulSoup(string, 'html.parser')

# Get all <option> tags in the string above
for option in soup.find_all('option'):
    dict = {}
    # Get the option value as country ID
    dict['id'] = option['value']
    # Get the text between opening & closing <option> tag as country name
    dict['name'] = option.text
    jsonfile.append(dict)       
   
with open("countries.json", mode="w", encoding="utf-8") as file:
    json.dump(jsonfile, file)
